In [ ]:
!pip install h5py

In [ ]:
import os
import h5py
import numpy as np
import cv2
filename = "/content/3DIMG_04OCT2021_0000_L1C_SGP_V01R00.h5"

with h5py.File(filename, "r") as f:
    root = f
    for key in root.keys():
      print(key)



data


In [ ]:
import h5py
import matplotlib.pyplot as plt

In [ ]:
print(data)

[[[ 678  678  679 ...  702  702 1023]
  [ 672  674  676 ...  701  701 1023]
  [ 668  669  671 ...  700  699 1023]
  ...
  [ 760  760  762 ...  821  819  820]
  [ 760  760  761 ...  821  818  819]
  [ 760  760  759 ...  820  816  815]]]


In [ ]:
data.lst

NameError: ignored

In [ ]:
nested_list = data.tolist()

NameError: ignored

In [ ]:
len(data)

1

In [ ]:
flat_list = your_2d_array.flatten()

In [ ]:
data.shape

(1, 3207, 3062)